# Generated by Django 6.0 on 2026-04-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_pricehistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categorys',
        ),
        migrations.AlterModelTable(
            name='pricehistory',
            table='products_price_history',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
