# Generated by Django 6.0 on 2026-04-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_category_table_alter_pricehistory_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
